### ISSUE TITLE
transporter and clientStorage onceAvailable()

### ISSUE THREAD

**Issue by JohannesMerz** [Hypheme/harmonized.js#16]
When the transporter/storage is down (for ex. no internet) and comes back up, it needs to resolve all promises returned by this method:

`clientStorage/transporter.onceAvailable().then(() => bla);
`

- [x] empty clientStorage
- [x] empty transporter
- [ ] http transporter

**Comment by tchock** [comment]
We should implement it in a way, that it doesn't need an endpoint to check connection at.

By default it should just check again after x seconds. When that isn't working, it should increase the pause between.

In the transporter/client storage there should be a static method to add checking endpoints. These checks could have multiple methods how to match routes that this checks cover:
* have a regexp where all offline transporter instances are matched against (for http transporter)
* you can also manually link transporter instances to offline checkers

Other methods could also be possible, because for different implementations different methods are needed.

I think every implementation (like HTTP, indexeddb, etc.) should have different offline checker methods, but they all should have the same interface to connect offline checkers with transporter/client storage instances.

@JohannesMerz what do you think about this?

**Comment by JohannesMerz** [comment]
What do you mean by checking? Just say, im available again and the Item tries another call?  That may be pretty heavy (imagine like 20 Items that are waiting) just for a check.

Another idea: when resolving all the promises, we should do it async, so that not all promises gets resolved at once and everything freezes

**Comment by tchock** [comment]
Generally offline matchers can be linked to multiple transporter instances, so only one (or a few) endpoints are tested at a time.

Here are some scenarios for different implementations:

## EmptyTransporter and EmptyClientStorage
onceAvailable() will directly resolve, because these implementations don't have any connection to a database or server.

## HttpTransporter
### Endpoint has no matching "offline checker"
After an request failed because of missing connection it will check after x seconds. When that fails, it will try in 2*x seconds. After that, 4*x seconds, etc. The pause can't be longer than y seconds.

This automatically creates a "offline checker" for this transporter. In general "offline checkers" should chunk resolving, so there are only a few requests done at once (like @JohannesMerz  described).

In the future this version of "offline checking" could be more sophisticated. When there are multiple endpoints offline, it could try to get the common denominator for those. Those that can't find one, will be handled separately. From those grouped endpoints, only one will be checked until it works again. Then the rest will be sent. But for the start even chunking should be postponed for future milestones.

### Endpoint matches "offline checker" by regExp
A transporter instance is created. On creation it will try to receive the matching offline checker instance through a static method of the HTTP Transporter (which needs to be there on every transporter/client storage implementation). There are offline checkers registered to the static transporter. The static matching method will run through all offline checkers available and will return the matching regexp that were registered with the base class.

Let's say the base url is "https://api.hyphe.me/v1" and the route is "cars/123/wheels/321". 
There are multiple matchers there:
* `/https:\/\/api.hyphe.me\/v1\/passengers\/.*/`
* `/https:\/\/api.hyphe.me\/v1\/cars\/.*/`
* `/https:\/\/api.hyphe.me\/v2\/.*/`

Both 'cars' and 'passengers' endpoints come from different servers, so there should be different offline checks for the different routes.
The combined url ("https://api.hyphe.me/v1/cars/123/wheels/321") is checked against all regexps until the first is found, so it will match `/https:\/\/api.hyphe.me\/v1\/cars/`.

This could also be done glob based (when the test pattern is a string instead of regexp), like:
* `'https://www.hyphe.me/v1/passengers/*'`
* `'https://www.hyphe.me/v1/*/subfield'`
* `'https://www.hyphe.me/v1/**/blub/*'`
* `'https://www.hyphe.me/v*/*'`

### Endpoint is linked directly to "offline checker"
On creation of a HTTP transporter instance this is directly linked to a "offline checker". When offline it will wait for this offline checker to resolve.

## IndexedDB
This will be easy, because this should know the connections. So when the connection to the database is established again, then onceAvailable() will be resolved.

## WebSockets
This also is easy, because it behaves like IndexedDB. Connections for multiple endpoints share one connection and the connections are active.
